### ISSUE TITLE
[Documentation] HowTo Usage

### ISSUE THREAD

**Issue by rubyFeedback** [aatwo/TheWiggler#1]
Hello there,

Found the link on reddit. If you have some time in the next months,
could you:

a) write a short usage + compilation instruction? Does not have to be long, a sentence or two.
b) perhaps explain very briefly how it works? Again nothing long, just a starter for people to want to understand and get an early "jump-starter" how that works or is different from xdotool or whatever the commandline variants were called on linux (I forgot the name but I thought it was xdotool or something like that).

Thanks!

**Comment by aatwo** [comment]
Sure I can. Sorry I didn't think to add that info initially!

**Comment by aatwo** [comment]
Hopefully what I have added to the readme is sufficient =)
