### ISSUE TITLE
A freeware product for the same purpose has been available for some time.

### ISSUE THREAD

**Issue by jroughgarden** [aatwo/TheWiggler#4]
There is a freeware product that seems to do the same thing as The Wiggler. It's called Caffeine and is available at https://www.zhornsoftware.co.uk/. I used it for a while when I was working from home and was being monitored by management. Seems to have worked fine.

That being said, I don't mean to diminish your work.

**Comment by aatwo** [comment]
Hello. Thanks very much for the link I appreciate it. I've certainly heard about Caffeine and a few alternative anti-PC locking applications however in this instance I found myself with a degree of free time and the motivation to brush up on my Qt skills!
